development:
  adapter: postgresql
  encoding: unicode
  database: track_env
  pool: 5
  username: postgres
  password: 1234

test:
  adapter: postgresql
  encoding: unicode
  database: track_env
  pool: 5
  username: postgres
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: track_env
  pool: 5
  username: postgres
  password: 1234
